config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  get 'homes/about' => 'homes#about'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :index, :edit, :create, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,  length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

         attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?



    def after_sign_in_path_for(resource)
      books_path
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :check_user,{only: [:edit]}


  def new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was created!"
      redirect_to books_path
    else
      @books = Book.all
      @new_book = Book.new(book_params)
      flash[:false] = "false Create book..."
      render :index
    end

  end

  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @books = Book.all
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was update!"
      redirect_to book_path(@book.id)
    else
      render edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def check_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = @user.books
    @book_all = Book.all
    @new_book = Book.new

  end

  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def edit
    @users = User.find(params[:id])
    @user = current_user
    if current_user != @users.id
      redirect_to user_path(@user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_iamge, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>

<%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg" %>


<table class="table">


  <tbody>

    <tr></tr>

    <tr>
      <th>name</th>
      <th><%= user.name %></th>

    </tr>

    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

  </tbody>




</table>



<div class="row">

  <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

</div>




<h2 class="mt-3">New book</h2>




<%= form_with model:new_book, local:true do |f| %>

  <%= f.text_field :title, class: "form-control" %>

  <%= f.text_area :body, class: "form-control mt-3" %>

  <%= f.submit 'Create', class: "btn btn-success mt-3" %>

<% end %>









</form>

app/views/books/edit.html.erb
 <p id="notice"></p>

<div class="container">

  <% if @book.errors.any? %>
        <%= @book.errors.count %>error
        <% @book.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>

  <div class="row">

  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h2>Editing Book</h2>

    <div class="table">

      <%= form_with model: @book, local:true do |f| %>


        <h4 class="mt-4">
          Title
          </h4>
            <%= f.text_field :title, class:"mt-4 form-control" %></td>

        <h4 class="mt-4">
          Opinion
           </h4>
            <%= f.text_area :body, class:"mt-4 form-control" %></td>

            <%= f.submit 'Update', class:"btn btn-primary mt-4" %>


      <% end %>

    </div>

    <%= link_to "Show", book_path(@book.id) %>

    <span>|</span>

    <%= link_to "Back", books_path %>



  </div>

</div>



  </div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <% if @new_book.errors.any? %>
        <%= @new_book.errors.count %>error
        <% @new_book.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>

  <div class="row">
    <div class="col-md-3">

      <%= render "books/list", user: @user, new_book: @new_book %>

    </div>




      <div class="col-md-8 offset-md-1">

         <h2>Books</h2>

      <div class="table">
        <table>
          <tr>
            <td></td>
            <td></td>
            <td>Title</td>
            <td></td>
            <td>Opinion</td>
          </tr>
        </table>
      </div>

       <div class="tabele">

        <% @books.each do |book| %>

          <table class="table table-hover table-inverse">

            <tr>

            <td>

            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "minino-image-icon.jpg" %>
            <% end %>

            </td>


              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>

            </tr>
          </table>


        <% end %>

      </div>









    </div>

  </div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0 mt-4">
  <div class="row">
    <div class="col-md-3">


      <%= render "books/list", user: @user, new_book: @new_book %>

      </div>
      <div class="col-md-8 offset-md-1">

        <h2>Book detail</h2>


      <div class="table">
        <table>
          <tr>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-primary" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "destoroy", book_path(@book), class:"btn btn-danger", method: :delete, "data-confirm" => "お前マジか..？" %>

              <% end %>
            </td>
          </tr>
        </table>

      </div>


      </div>


  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>


<div class="container">


  <div class="row">


    <h1 class="px-3 mx-auto">

      Welcome to

      <i class="fas fa-book"></i>


      <strong>Bookers</strong>!

    </h1>

  </div>


</div>

app/views/homes/top.html.erb
<p id="notice"></p>



<div class="container">


<div class="row">


<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

    <h1>

      welcome to <i class="fas fa-book"></i>

      <strong>Bookers</strong>

    </h1>

    <p>

      In

      <i class="fas fa-book"></i>

      <strong>Bookers,</strong>




    </p>

    <p>you can share and exchange  your opinions , inpressions , and emotions</p>


    <p> about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">


      <div class="row">

       <%= link_to "log in", user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>

      </div>


      <div class="row">

        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>

      </div>


    </div>

  </div>



  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container">

          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>





          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">


          <span class="navbar-toggler-icon"></span>


          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">


            <% if user_signed_in? %>
                <li>

                <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>

              </li>

              <li>

                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>

              </li>

              <li>

                <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>

              </li>

              <li>

                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>

              </li>
              <% else %>
                  <li>

                <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>

              </li>

              <li>

                <%= link_to "about", homes_about_path, class: "fas fa-link nav-link text-light" %>

              </li>


              <li>

                <%= link_to "log in", user_session_path, class: "fas fa-user-plus nav-link text-light" %>

              </li>

              <li>

                <%= link_to "sign up", new_user_registration_path, class: "fas fa-sign-in-alt nav-link text-light" %>

              </li>
            <% end %>


            </ul>


          </div>

        </div>


        </nav>

      </header>
    <main>

      <p><%= flash[:notice] %></p>

      <p><%= flash[:false] %></p>


      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>

    </footer>

  </body>
</html>

app/views/layouts/アプリケーションのkeep.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h2>
      Bookers2
    </h2>
     <% if user_signed_in? %>

     <li>
        <%= link_to "Home", user_path(current_user) class: "btn btn-succece" %>
      </li>
     <li>
        <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
      </li>
     <li>
        <%= link_to "Books", books_path, %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>

    <% else %>
      <li>
        <%= link_to "Home", root_path, class: "btn btn-succece"  %>
      </li>
     <li>
        <%= link_to "About", destroy_user_session_path,  %>
      </li>
     <li>
        <%= link_to "sign up", destroy_user_session_path,  %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path,  %>
      </li>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>

<div class="container">

  <% if @users.errors.any? %>
        <%= @users.errors.count %>error
        <% @users.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>

  <div class="row">

    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <div class="form">

        <%= form_with model:@users, local:true do |f| %>


        <h2>User info</h2>


        <h4>Name</h4>

        <%= f.text_field :name, autofocus: true, id:"name", class:"form-control name" %>


        <h4>image</h4>

        <%= f.attachment_field :profile_image %>


        <h4>introduction</h4>

        <%= f.text_area :introduction, class: "form-control" %>

        <%= f.submit 'Update', class:"btn btn-success" %>

        <% end %>


    </div>

  </div>

</div>

app/views/users/index.html.erb
<p id="notice"></p>


<div class="container px-5 px-sm-0">

<div class="row">


<div class="col-md-3">

<%= render "books/list", user: @user, new_book: @new_book %>


</div>


    <div class="col-md-8 offset-md-1">

      <h2>Users</h2>

      <div class="table table-hover">

        <table>
          <tr>
            <td>image</td>
            <td>name</td>
          </tr>
        </table>

        <table>
          <% @users.each do |user| %>
          <tr>
            <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "minino-image-icon.jpg" %>
            </td>
            <td><%= user.name %></td>
            <td><%=link_to "Show", user_path(user.id) %></td>
          </tr>

          <% end %>

        </table>

      </div>


    </div>

  </div>


</div>

app/views/users/show.html.erb
<div "container">
  
  <p id="notice"></p>
  
  <div class="row">

    <div class="col-md-3">
      <%= render "books/list", user: @user, new_book: @new_book %>

     </div>

<div class="col-md-8 offset-md-1">

  <div class="table">
    <table>
      <tr>
        <td>Title</td>
        <td>Opinion</td>
      </tr>
    </table>
  </div>
  <div>

  </div>

  <div>

    <% @books.each do |book| %>
      <%= link_to book_path(book.user) do %>
      <%= attachment_image_tag @users, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "minino-image-icon.jpg" %>
    <% end %>
    <%= link_to book.title, book_path(book.id) %>
    <%= book.body %>


<% end %>

  </div>



</div>

</div>

</div>